SHOW DATABASES;
set autocommit = 0;
select @@autocommit;
create database cyber;
use cyber;
CREATE TABLE ACCOUNTS(
ID INT PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(50),
BALANCE DECIMAL(10,2)
);
INSERT INTO ACCOUNTS 
(NAME,BALANCE)
VALUES
("ADAM",500.00),
("BOB",300.00),
("CHARLIE",1000.00);
SELECT * FROM ACCOUNTS;
SELECT* FROM ACCOUNTS;
START transaction;
SELECT* FROM ACCOUNTS;

START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
commit;
SELECT* FROM ACCOUNTS;
SET AUTOCOMMIT = 0;

START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
UPDATE ACCOUNTS SET BALANCE=BALANCE+100 WHERE ID = 1;
COMMIT;
SELECT* FROM ACCOUNTS;
START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
UPDATE ACCOUNTS SET BALANCE=BALANCE+100 WHERE ID = 1;
COMMIT;
SELECT* FROM ACCOUNTS;
START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
UPDATE ACCOUNTS SET BALANCE=BALANCE+100 WHERE ID = 1;
SAVEPOINT BALANCE_UPDATED;
UPDATE ACCOUNTS SET BALANCE=BALANCE+10 WHERE ID=3;
ROLLBACK BALANCE_UPDATED;
START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
UPDATE ACCOUNTS SET BALANCE=BALANCE+100 WHERE ID = 1;
SAVEPOINT BALANCE_UPDATED;
UPDATE ACCOUNTS SET BALANCE=BALANCE+10 WHERE ID=3;
ROLLBACK TO BALANCE_UPDATED;
SELECT* FROM ACCOUNTS;
START transaction;
UPDATE ACCOUNTS SET BALANCE=BALANCE-100 WHERE ID=3;
UPDATE ACCOUNTS SET BALANCE=BALANCE+100 WHERE ID = 1;
SAVEPOINT BALANCE_UPDATED;
UPDATE ACCOUNTS SET BALANCE=BALANCE+10 WHERE ID=3;
ROLLBACK TO BALANCE_UPDATED;
COMMIT;
SELECT* FROM ACCOUNTS;
CREATE TABLE CUSTOMERS(
CUSTOMER_ID INT PRIMARY KEY,
NAME VARCHAR(50),
CITY VARCHAR(50)
);

INSERT INTO CUSTOMERS
(CUSTOMER_ID,NAME,CITY)
VALUES
(1,"ALICE","MUMBAI"),(2,"BOB","DELHI"),(3,"CHARLIE","BANGLORE"),(4,"DAVID","MUMBAI");
SELECT* FROM CUSTOMERS;
CREATE TABLE ORDERS(
ORDER_ID INT PRIMARY KEY,
CUSTOMER_ID INT,
AMOUNT int
);
INSERT INTO ORDERS
(ORDER_ID,CUSTOMER_ID,AMOUNT)
VALUES
(101,1,500),(102,1,900),(103,2,300),(104,5,700);
SELECT* FROM ORDERS;
SELECT * FROM CUSTOMERS AS C LEFT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE O.CUSTOMER_ID IS NULL;
SELECT * FROM CUSTOMERS AS C RIGHT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL;
SELECT * FROM CUSTOMERS WHERE CUSTOMER_ID > 2;
SELECT * FROM CUSTOMERS AS C RIGHT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE C.CUSTOMER_ID IS NULL;
SELECT * FROM CUSTOMERS AS C LEFT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID WHERE O.CUSTOMER_ID IS NULL;

SELECT * FROM ORDERS WHERE AMOUNT > (SELECT AVG(AMOUNT) FROM ORDERS);

SELECT NAME , (SELECT COUNT(*) FROM ORDERS AS O WHERE O.CUSTOMER_ID = C.CUSTOMER_ID ) AS ORDER_COUNT FROM CUSTOMERS AS C;
SELECT CUSTOMER_ID , AVG(AMOUNT) AS AVG_AMOUNT FROM ORDERS GROUP BY CUSTOMER_ID;
SELECT* FROM ORDERS;
SELECT CUSTOMER_ID , AVG(AMOUNT) AS AVG_AMOUNT FROM ORDERS GROUP BY CUSTOMER_ID;

SELECT * FROM CUSTOMERS AS C RIGHT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID 
UNION
SELECT * FROM CUSTOMERS AS C LEFT JOIN ORDERS AS O ON C.CUSTOMER_ID = O.CUSTOMER_ID;
create view view1 as 
select name,city from customers;
SELECT * FROM VIEW1;

DROP TABLE ACCOUNTS;

CREATE TABLE  ACCOUNTS (
ACCOUNT_ID INT PRIMARY KEY,
NAME VARCHAR(50),
BALANCE DECIMAL(10,2),
BRANCH VARCHAR(50)
);

INSERT INTO ACCOUNTS
(ACCOUNT_ID,NAME,BALANCE,BRANCH)
VALUES
(1,"ADAM",500,"MUMBAI"),
(2,"BOB",300.00,"DELHI"),
(3,"CHARLIE",700.00,"BANGLORE"),
(4,"DAVID",1000,"NOIDA");

SELECT* FROM ACCOUNTS;

DELIMITER $$
CREATE PROCEDURE CHECK_BALANCE(IN ACC_ID INT , OUT BAL DECIMAL(10,2))
BEGIN
SELECT BALANCE INTO BAL FROM ACCOUNTS AS A
WHERE A.ACCOUNT_ID=ACC_ID;
END$$

DELIMITER ;

CALL CHECK_BALANCE (4,@BALANCE);
SELECT @BALANCE;
